# Generated by Django 6.1 on 2026-08-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('subtitle', models.CharField(blank=True, help_text="Ex.: 'The Intelligence Network' para a Nexa.", max_length=200)),
                ('tag', models.CharField(help_text="Rótulo curto mostrado no cartão. Ex.: 'Plataforma de IA', 'FinTech'.", max_length=80)),
                ('category', models.CharField(choices=[('produtos', 'Produtos'), ('ia', 'IA'), ('software', 'Software'), ('investigacao', 'Investigação'), ('fintech', 'Fintech'), ('healthtech', 'HealthTech'), ('educacao', 'Educação'), ('prototipos', 'Protótipos')], max_length=20)),
                ('status', models.CharField(choices=[('desenvolvimento', 'Em desenvolvimento'), ('investigacao', 'Em investigação'), ('prototipo', 'Protótipo'), ('activo', 'Activo'), ('arquivado', 'Arquivado')], max_length=20)),
                ('short_description', models.CharField(help_text='Descrição usada nos cartões de projecto.', max_length=280)),
                ('long_description', models.TextField(blank=True, help_text='Descrição completa usada na página de detalhe.')),
                ('technologies', models.CharField(blank=True, help_text="Lista separada por vírgulas. Ex.: 'Python, Machine Learning, APIs'.", max_length=300)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('external_url', models.URLField(blank=True)),
                ('is_flagship', models.BooleanField(default=False, help_text='Projectos com página própria dedicada (ex.: Nexa, KIVA).')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de apresentação (menor primeiro).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
