# Generated by Django 6.1 on 2026-08-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Ex.: 'LISPA Hackathon'.", max_length=150)),
                ('type', models.CharField(choices=[('award', 'Prémio / Resultado'), ('participation', 'Participação')], default='participation', max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('related_project', models.CharField(blank=True, help_text="Ex.: 'SaúdeLink'.", max_length=150)),
                ('result', models.CharField(blank=True, help_text="Ex.: 'Vencedores / 1.º lugar'. Deixar vazio se não confirmado.", max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Reconhecimento',
                'verbose_name_plural': 'Reconhecimentos',
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Formato internacional sem espaços, ex.: 244936069611. Usado para construir o link https://wa.me/<numero>.', max_length=20)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='Deixar vazio até existir o URL real da organização.')),
                ('github_url', models.URLField(blank=True, help_text='Deixar vazio até existir o URL real da organização.')),
                ('metric_projects', models.PositiveIntegerField(blank=True, null=True, verbose_name='Projectos desenvolvidos')),
                ('metric_hackathons', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hackathons & programas')),
                ('metric_partners', models.PositiveIntegerField(blank=True, null=True, verbose_name='Parceiros')),
                ('metric_people_reached', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pessoas alcançadas')),
                ('metric_technologies', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tecnologias utilizadas')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do site',
                'verbose_name_plural': 'Configuração do site',
            },
        ),
    ]
