# Generated by Django 6.1 on 2026-08-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='department',
            field=models.CharField(choices=[('leadership', 'Leadership / Founding Team'), ('engineering', 'Engineering'), ('research', 'Research & Innovation'), ('product', 'Product & Design'), ('business', 'Business & Strategy'), ('communication', 'Communication')], max_length=20),
        ),
    ]
