# Generated by Django 6.1 on 2026-08-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_teammember_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='areas',
            field=models.CharField(blank=True, help_text="Lista separada por vírgulas para o perfil individual. Ex.: 'Software Engineering, Artificial Intelligence'.", max_length=250),
        ),
        migrations.AddField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, unique=True),
        ),
    ]
