# Generated by Django 6.1 on 2026-08-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('company', models.CharField(blank=True, max_length=150, verbose_name='Empresa / Organização')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefone')),
                ('project_type', models.CharField(choices=[('software', 'Software'), ('ia', 'Inteligência Artificial'), ('dados', 'Dados & Analytics'), ('consultoria', 'Consultoria'), ('parceria', 'Parceria'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo de projecto')),
                ('budget', models.CharField(blank=True, max_length=100, verbose_name='Orçamento aproximado')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled', models.BooleanField(default=False, verbose_name='Tratado')),
            ],
            options={
                'verbose_name': 'Pedido de contacto',
                'verbose_name_plural': 'Pedidos de contacto',
                'ordering': ['-created_at'],
            },
        ),
    ]
