# Generated by Django 6.1 on 2026-08-19 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('summary', models.CharField(max_length=300)),
                ('content', models.TextField(help_text='Suporta Markdown/HTML simples conforme o template do artigo.')),
                ('category', models.CharField(choices=[('ia', 'Inteligência Artificial'), ('software', 'Software Engineering'), ('ciencia', 'Ciência'), ('tecnologia', 'Tecnologia'), ('programacao', 'Programação'), ('dados', 'Dados'), ('investigacao', 'Investigação'), ('empreendedorismo', 'Empreendedorismo Tecnológico')], max_length=20)),
                ('author_name', models.CharField(max_length=120)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('reading_time_minutes', models.PositiveIntegerField(default=5)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('related_articles', models.ManyToManyField(blank=True, to='blog.article')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
